site_name: Project Wiki

nav:
  - Home: index.md
  - Setup Guides: docs/setup
  - Roadmap: docs/roadmap
  - Development: docs/development
  - Logs: docs/logs
  - Troubleshooting:
      - Wi-Fi Driver: docs/troubleshooting/wifi-driver.md
  - Tags: tags.md

theme:
  name: material

plugins:
  - search
  - awesome-pages
  - tags

dev_addr: 0.0.0.0:8000

extra_css: []
extra_templates: []
docs_dir: docs

extra_javascript:
  - js/custom.js
