[build]
  publish = "site"
  command = "mkdocs build && cp -r admin site/"

[build.environment]
  PYTHON_VERSION = "3.12"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

